### ISSUE TITLE
need to ignore ansible-core patch

### ISSUE THREAD

**Issue by chenrui333** [Homebrew/brew-pip-audit#128]
For [such PR](https://github.com/Homebrew/homebrew-core/pull/197793), while it tries to patch ansible-core for ansible-lint, but it would make ansible-lint effectively use a different version of ansible-core other than ansible (which would cause some runtime issue).

I wonder if it would be possible just to ignore such security update (currently we are just waiting for ansible 11 release)

cc @daeho-ro

**Comment by woodruffw** [comment]
Leaving the PR open as a draft *should* mean that no new PRs will be created for `ansible`, so this should solve itself. But if you'd like me to add it to the ignore list as well, I can do that.

**Comment by chenrui333** [comment]
@woodruffw adding to the ignore list would be a good idea, I just created a pr for it. thanks for the pointer. :)
