### ISSUE TITLE
PR automation: follow-ups

### ISSUE THREAD

**Issue by woodruffw** [Homebrew/brew-pip-audit#19]
Some things we should do:

- [ ] Bump the `revision` as well, so that auto-bumped formulae are automatically pushed to users who `brew upgrade` (#44);
- [x] Issue PRs in alphabetical order, so that we have a rough idea of how much progress the automation has made;
- [x] Look into throttling the PR automation when triggered periodically to avoid spamming the `homebrew-core` maintainers.
- [x] Look into replacing `pipgrip` within Homebrew for dep upgrades, since it uses Poetry's resolver and is slow/does different resolutions than `pip`
    - [x] https://github.com/Homebrew/brew/pull/15307
- [x] Don't send a PR if it doesn't actually fix a vulnerability. This happens when version constraints don't allow upgrading the vulnerable dep, but there are other packages to be updated (example: https://github.com/Homebrew/homebrew-core/pull/122902).
- [x] Include the list of fixed vulnerabilities in the PR message.

**Comment by alex** [comment]
Another follow up:

- Don't send a PR if it doesn't actually fix a vulnerability. This happens when version constraints don't allow upgrading the vulnerable dep, but there are other packages to be updated (example: https://github.com/Homebrew/homebrew-core/pull/122902).

**Comment by woodruffw** [comment]
Yep. Similarly, we should include *which* vulnerabilities we're submitting the PR for in the PR message.

**Comment by alex** [comment]
- [ ] re-enable automation

we disabled this because PRs started getting screwed up: they duplicated resources instead of replacing them

**Comment by alex** [comment]
Automation is now re-enabled

**Comment by woodruffw** [comment]
> * Don't send a PR if it doesn't actually fix a vulnerability. This happens when version constraints don't allow upgrading the vulnerable dep, but there are other packages to be updated (example: [cyral-gimme-db-token: bump python resources homebrew-core#122902](https://github.com/Homebrew/homebrew-core/pull/122902)).

Looking into this one now.

**Comment by woodruffw** [comment]
> Include the list of fixed vulnerabilities in the PR message.

#35 will include this, although not in its ideal form: it'll list each distribution URL known to be vulnerable, and each one that was successfully auto-updated.

**Comment by woodruffw** [comment]
Sniping myself into doing the revision bumping today.

**Comment by woodruffw** [comment]
#44 should be the last part of this.
