### ISSUE TITLE
Attempt to auto-send PRs to brew

### ISSUE THREAD

**Issue by alex** [Homebrew/brew-pip-audit#6]
Ideally for any formula that we identify vulnerabilities in we'd:

- Bump dependencies (`brew update-python-resources`)
- Verify that this fixes vulnerabilities
- ~Bump revision~
- Send a PR to homebrew

This would significantly reduce the burdens of keeping the ecosystem secure

**Comment by woodruffw** [comment]
> * Send a PR to homebrew

I think this last step will be the fiddliest/most annoying -- I'm not sure if actions are allowed to create PRs on arbitrary repositories.

The rest should be pretty straightforward, though!

**Comment by alex** [comment]
Yes I think that's correct -- it may require adding a secret to the env manually.

**Comment by woodruffw** [comment]
Migrated over to the Homebrew org, so this will hopefully be a little easier. I'll take a stab it soon.

**Comment by alex** [comment]
We now send them.

We need to have them add/bump `revision` though.

**Comment by woodruffw** [comment]
Yeah, I'll make a separate follow-up for that and the other things we identified.
